config/routes.rb
Rails.application.routes.draw do
  get("/", { :controller => "misc", :action => "homepage" })
  
  get("/applicants/:id/profile", { :controller => "applicants", :action => "profile", :as => "applicant_profile" })
  get("/employers/:id/profile", { :controller => "employers", :action => "profile", :as => "employer_profile" })

  # Routes for the Bookmarked job resource:

  # CREATE
  post("/insert_bookmarked_job", { :controller => "bookmarked_jobs", :action => "create" })
          
  # READ
  get("/bookmarked_jobs", { :controller => "bookmarked_jobs", :action => "index" })
  
  # get("/bookmarked_jobs/:path_id", { :controller => "bookmarked_jobs", :action => "show" })
  
  # # UPDATE
  # post("/modify_bookmarked_job/:path_id", { :controller => "bookmarked_jobs", :action => "update" })
  
  # DELETE
  post("/delete_bookmarked_job/:path_id", { :controller => "bookmarked_jobs", :action => "destroy" })

  #------------------------------

  # Routes for the Job posting resource:

  # Employers can post after sign-in which gets updated to the job posting database
  # Then employer can view the job postings they have posted (not from other employers), and update individual job postings
  # Applicants can see all job postings from all employers (including bookmark status from themselves)
  # Applicants can add / remove bookmark to individual posting

  # CREATE
  post("/insert_job_posting", { :controller => "job_postings", :action => "create" }) #for employers

  # READ
  get("/job_postings/new", { :controller => "job_postings", :action => "new"}) #for employers

  get("/job_postings", { :controller => "job_postings", :action => "index" }) #for applicants

  get("/job_postings/employers/:id", { :controller => "job_postings", :action => "employ" }) #for employers
  
  # get("/job_postings/:id", { :controller => "job_postings", :action => "show" })

  get("/job_postings/:id/edit", { :controller => "job_postings", :action => "edit" }) #for employers
  
  # UPDATE
  
  post("/job_postings/:id/edit", { :controller => "job_postings", :action => "update" })
  
  # # DELETE
  # get("/delete_job_posting/:path_id", { :controller => "job_postings", :action => "destroy" })

  #------------------------------

  devise_for :employers, path: 'employers'
  devise_for :applicants, path: 'applicants'
  
end

app/models/employer.rb
# == Schema Information
#
# Table name: employers
#
#  id                       :bigint           not null, primary key
#  company_description      :text
#  email                    :string           default(""), not null
#  encrypted_password       :string           default(""), not null
#  for_profit_or_non_profit :string
#  industry                 :string
#  job_postings_count       :integer
#  name                     :string
#  remember_created_at      :datetime
#  reset_password_sent_at   :datetime
#  reset_password_token     :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#
# Indexes
#
#  index_employers_on_email                 (email) UNIQUE
#  index_employers_on_reset_password_token  (reset_password_token) UNIQUE
#
class Employer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many  :job_postings, class_name: "JobPosting", foreign_key: "employer_id", dependent: :destroy

  # validates :name, presence: true

  # validates :industry, presence: true

  # validates :for_profit_or_non_profit, presence: true

  # validates :company_description, presence: true
end

app/controllers/employer_controller.rb
class EmployersController < ApplicationController
  def profile
    @employer = Employer.find(params[:id]) # Find the specific employer by ID

    render({ :template => "employers/profile" })
  end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  def profile
    @employer = Employer.find(params[:id]) # Find the specific employer by ID

    render({ :template => "employers/profile" })
  end
end

app/views/employers/job_postings.html.erb
<h1>Job Postings</h1>

<% if @job_postings.any? %>
  <table border="1">
    <thead>
      <tr>
        <th>Title</th>
        <th>Employer Name</th>
        <th>Industry</th>
        <th>Responsibilities</th>
        <th>Desired Qualifications</th>
        <th>Logistics</th>
        <th>Pay Range</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @job_postings.each do |job| %>
        <tr>
          <td><%= job.title %></td>
          <td><%= job.employer.name %></td>
          <td><%= job.employer.industry %></td>
          <td><%= job.responsibilities %></td>
          <td><%= job.desired_qualifications %></td>
          <td><%= job.logistics %></td>
          <td><%= job.pay_range %></td>
          <td>
            <%= link_to "Modify", "/job_postings/#{job.id}/edit", class: "btn btn-secondary" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No job postings available.</p>
<% end %>

<%= link_to "Back to Profile", employer_profile_path(current_employer.id), class: "btn btn-primary" %>

app/views/employers/profile.html.erb
<h1>Welcome, <%= @employer.name %>!</h1>

<body>
    
    <p>Here is your profile information</p>
    <p>Email: <%= @employer.email %></p>
    <p>Industry: <%= @employer.industry %></p>
    <p>For-Profit/Non-Profit: <%= @employer.for_profit_or_non_profit %></p>
    <p>Company Description: <%= @employer.company_description %></p>

  <div>
    <a href="/job_postings/new">Add job postings</a>
  </div>
  <div>
    <a href="/job_postings/employers/:id">View existing job postings</a>
  </div>
</body>