config/routes.rb
Rails.application.routes.draw do
  get("/", { :controller => "misc", :action => "homepage" })
  
  get("/applicants/:id/profile", { :controller => "applicants", :action => "profile", :as => "applicant_profile" })
  get("/employers/:id/profile", { :controller => "employers", :action => "profile", :as => "employer_profile" })

  # Routes for the Bookmarked job resource:

  # CREATE
  post("/insert_bookmarked_job", { :controller => "bookmarked_jobs", :action => "create" })
          
  # READ
  get("/bookmarked_jobs", { :controller => "bookmarked_jobs", :action => "index" })
  
  # get("/bookmarked_jobs/:path_id", { :controller => "bookmarked_jobs", :action => "show" })
  
  # # UPDATE
  # post("/modify_bookmarked_job/:path_id", { :controller => "bookmarked_jobs", :action => "update" })
  
  # DELETE
  post("/delete_bookmarked_job/:path_id", { :controller => "bookmarked_jobs", :action => "destroy" })

  #------------------------------

  # Routes for the Job posting resource:

  # Employers can post after sign-in which gets updated to the job posting database
  # Then employer can view the job postings they have posted (not from other employers), and update individual job postings
  # Applicants can see all job postings from all employers (including bookmark status from themselves)
  # Applicants can add / remove bookmark to individual posting

  # CREATE
  post("/insert_job_posting", { :controller => "job_postings", :action => "create" }) #for employers

  # READ
  get("/job_postings/new", { :controller => "job_postings", :action => "new"}) #for employers

  get("/job_postings", { :controller => "job_postings", :action => "index" }) #for applicants

  get("/job_postings/employers/:id", { :controller => "job_postings", :action => "employ" }) #for employers
  
  # get("/job_postings/:id", { :controller => "job_postings", :action => "show" })

  get("/job_postings/:id/edit", { :controller => "job_postings", :action => "edit" }) #for employers
  
  # UPDATE
  
  post("/job_postings/:id/edit", { :controller => "job_postings", :action => "update" })
  
  # # DELETE
  # get("/delete_job_posting/:path_id", { :controller => "job_postings", :action => "destroy" })

  #------------------------------

  devise_for :employers, path: 'employers'
  devise_for :applicants, path: 'applicants'
  
end

app/models/job_posting.rb
# == Schema Information
#
# Table name: job_postings
#
#  id                     :bigint           not null, primary key
#  bookmarked_jobs_count  :integer
#  desired_qualifications :text
#  industry               :string
#  logistics              :text
#  pay_range              :string
#  responsibilities       :text
#  title                  :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  employer_id            :integer
#

class JobPosting < ApplicationRecord
  belongs_to :employer, required: true, class_name: "Employer", foreign_key: "employer_id", counter_cache: true

  has_many  :bookmarked_jobs, class_name: "BookmarkedJob", foreign_key: "job_posting_id", dependent: :destroy

  has_many :interested_applicants, through: :bookmarked_jobs, source: :applicants

  validates :title, presence: true

  validates :responsibilities, presence: true

  validates :pay_range, presence: true

  validates :logistics, presence: true

  validates :desired_qualifications, presence: true
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  def edit
    the_id = params.fetch("id")
    @the_job_posting = JobPosting.where({ :id => the_id }).at(0)
    
    render({ :template => "job_postings/edit" })
  end
  
  def new
    render({ :template => "job_postings/new"})
  end

  def employ
    @job_postings = current_employer.job_postings
    render({ :template => "employers/job_postings" })
  end

  def index
    matching_job_postings = JobPosting.all

    @list_of_job_postings = matching_job_postings.order({ :created_at => :desc })

    render({ :template => "job_postings/index" })
  end

  # def show
  #   the_id = params.fetch("path_id")

  #   matching_job_postings = JobPosting.where({ :id => the_id })

  #   @the_job_posting = matching_job_postings.at(0)

  #   render({ :template => "job_postings/show" })
  # end

  def create
    the_job_posting = JobPosting.new
    the_job_posting.title = params.fetch("query_title")
    the_job_posting.responsibilities = params.fetch("query_responsibilities")
    the_job_posting.desired_qualifications = params.fetch("query_desired_qualifications")
    the_job_posting.logistics = params.fetch("query_logistics")
    the_job_posting.pay_range = params.fetch("query_pay_range")
    the_job_posting.employer_id = current_employer.id
    the_job_posting.industry = current_employer.industry

    if the_job_posting.valid?
      the_job_posting.save
      redirect_to("/job_postings/employers/#{current_employer.id}", { :notice => "Job posting created successfully." })
    else
      redirect_to("/job_postings/employers/#{current_employer.id}", { :alert => the_job_posting.errors.full_messages.to_sentence })
    end
  end

  def update
    the_id = params.fetch("id")
    the_job_posting = JobPosting.where({ :id => the_id }).at(0)

    the_job_posting.title = params.fetch("query_title")
    the_job_posting.responsibilities = params.fetch("query_responsibilities")
    the_job_posting.desired_qualifications = params.fetch("query_desired_qualifications")
    the_job_posting.logistics = params.fetch("query_logistics")
    the_job_posting.pay_range = params.fetch("query_pay_range")
    the_job_posting.employer_id = current_employer.id
    the_job_posting.industry = current_employer.industry

    if the_job_posting.valid?
      the_job_posting.save
      redirect_to("/job_postings/employers/#{current_employer.id}", { :notice => "Job posting updated successfully."} )
    else
      redirect_to("/job_postings/employers/#{current_employer.id}", { :alert => the_job_posting.errors.full_messages.to_sentence })
    end
  end

  # def destroy
  #   the_id = params.fetch("path_id")
  #   the_job_posting = JobPosting.where({ :id => the_id }).at(0)

  #   the_job_posting.destroy

  #   redirect_to("/job_postings", { :notice => "Job posting deleted successfully."} )
  # end
end

app/views/job_postings/edit.html.erb
<h1>Edit Job Posting</h1>

<%= form_with(model: @the_job_posting, url: "/job_postings/#{@the_job_posting.id}/edit", method: :post) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title, name: "query_title" %>
  </div>
  <div>
    <%= form.label :responsibilities %>
    <%= form.text_area :responsibilities, name: "query_responsibilities" %>
  </div>
  <div>
    <%= form.label :desired_qualifications %>
    <%= form.text_area :desired_qualifications, name: "query_desired_qualifications" %>
  </div>
  <div>
    <%= form.label :logistics %>
    <%= form.text_area :logistics, name: "query_logistics" %>
  </div>
  <div>
    <%= form.label :pay_range %>
    <%= form.text_field :pay_range, name: "query_pay_range" %>
  </div>
  <div>
    <%= form.submit "Update Job Posting" %>
  </div>
<% end %>

app/views/job_postings/index.html.erb
<div>
  <div>
    <h1>
      List of all job postings
    </h1>
  </div>
</div>

<hr>
<div>
  <div>
    <table border="1">
      <tr>
        <th>
          ID
        </th>

        <th>
          Title
        </th>

        <th>
          Responsibilities
        </th>

        <th>
          Desired qualifications
        </th>

        <th>
          Logistics
        </th>

        <th>
          Pay range
        </th>

        <th>
          Employer
        </th>

        <th>
          Industry
        </th>

        <th>
          Actions
        </th> 

      </tr>

      <% @list_of_job_postings.each do |a_job_posting| %>
      <tr>
        <td>
          <%= a_job_posting.id %>
        </td>

        <td>
          <%= a_job_posting.title %>
        </td>

        <td>
          <%= a_job_posting.responsibilities %>
        </td>

        <td>
          <%= a_job_posting.desired_qualifications %>
        </td>

        <td>
          <%= a_job_posting.logistics %>
        </td>

        <td>
          <%= a_job_posting.pay_range %>
        </td>

        <td>
          <% matching_employers = Employer.where({ :id => a_job_posting.employer_id }) %>
          
          <% the_employer = matching_employers.at(0) %>

          <%= the_employer.name %>
        </td>

        <td>
          <% matching_employers = Employer.where({ :id => a_job_posting.employer_id }) %>
          
          <% the_employer = matching_employers.at(0) %>

          <%= the_employer.industry %>
        </td>

        <td>
          <% if current_applicant.bookmarked_jobs.exists?({ :job_posting_id => a_job_posting.id }) %>
            <%= button_to "Remove Bookmark", "/delete_bookmarked_job/#{a_job_posting.id}", method: :post, class: "btn btn-danger" %>
          <% else %>
            <%= button_to "Bookmark", "/insert_bookmarked_job", method: :post, params: { job_posting_id: a_job_posting.id }, class: "btn btn-primary" %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

<%= link_to "Back to Profile", applicant_profile_path(current_applicant.id), class: "btn btn-primary" %>

<hr>

app/views/job_postings/new.html.erb
<div>
  <div>
    <h1>
      Create new job posting
    </h1>
  </div>
</div>

<hr>

<div>
  <form action="/insert_job_posting" method="post">
      <div>
        <label for="title_box">
          Title
        </label>

        <input type="text" id="title_box" name="query_title">
      </div>

      <div>
        <label for="responsibilities_box">
          Responsibilities
        </label>

        <textarea id="responsibilities_box" name="query_responsibilities" rows="6"></textarea>
      </div>

      <div>
        <label for="desired_qualifications_box">
          Desired qualifications
        </label>

        <textarea id="desired_qualifications_box" name="query_desired_qualifications" rows="6"></textarea>
      </div>

      <div>
        <label for="logistics_box">
          Logistics
        </label>

        <textarea id="logistics_box" name="query_logistics" rows="6"></textarea>
      </div>

      <div>
        <label for="pay_range_box">
          Pay range
        </label>

        <input type="text" id="pay_range_box" name="query_pay_range">
      </div>

<!--      <div>
        <input type="hidden" name="employer_id" value="<%#= current_employer.id %>">
      </div>-->

      <button>
        Add job posting
      </button>
    </form>
  </div>
</div>

<%= link_to "Back to Profile", employer_profile_path(current_employer.id), class: "btn btn-primary" %>
</hr>

app/views/job_postings/show.html.erb
<div>
  <div>
    <h1>
      Job posting #<%= @the_job_posting.id %> details
    </h1>

    <div>
      <div>
        <a href="/job_postings">
          Go back
        </a>
      </div>

      <div>
        <a href="/delete_job_posting/<%= @the_job_posting.id %>">
          Delete job posting
        </a>
      </div>
    </div>

    <dl>
      <dt>
        Title
      </dt>
      <dd>
        <%= @the_job_posting.title %>
      </dd>

      <dt>
        Responsibilities
      </dt>
      <dd>
        <%= @the_job_posting.responsibilities %>
      </dd>

      <dt>
        Desired qualifications
      </dt>
      <dd>
        <%= @the_job_posting.desired_qualifications %>
      </dd>

      <dt>
        Logistics
      </dt>
      <dd>
        <%= @the_job_posting.logistics %>
      </dd>

      <dt>
        Pay range
      </dt>
      <dd>
        <%= @the_job_posting.pay_range %>
      </dd>

      <dt>
        Employer
      </dt>
      <dd>
        <%= @the_job_posting.employer_id %>
      </dd>

<!--      <dt>
        Bookmarked count
      </dt>
      <dd>
        <%#= @the_job_posting.bookmarked_jobs_count %>-->
<!--      </dd>-->

      <dt>
        Created at
      </dt>
      <dd>
        <%= time_ago_in_words(@the_job_posting.created_at) %> ago
      </dd>

      <dt>
        Updated at
      </dt>
      <dd>
        <%= time_ago_in_words(@the_job_posting.updated_at) %> ago
      </dd>
    </dl>
  </div>
</div>

<hr>


<div>
  <div>
    <h2>
      Edit job posting
    </h2>

    <form action="/modify_job_posting/<%= @the_job_posting.id %>"  method="post" >
      <div>
        <label for="title_box">
          Title
        </label>

        <input type="text" id="title_box" name="query_title" value="<%= @the_job_posting.title %>">
      </div>

      <div>
        <label for="responsibilities_box">
          Responsibilities
        </label>

        <textarea id="responsibilities_box" name="query_responsibilities"><%= @the_job_posting.responsibilities %></textarea>
      </div>

      <div>
        <label for="desired_qualifications_box">
          Desired qualifications
        </label>

        <textarea id="desired_qualifications_box" name="query_desired_qualifications"><%= @the_job_posting.desired_qualifications %></textarea>
      </div>

      <div>
        <label for="logistics_box">
          Logistics
        </label>

        <textarea id="logistics_box" name="query_logistics"><%= @the_job_posting.logistics %></textarea>
      </div>

      <div>
        <label for="pay_range_box">
          Pay range
        </label>

        <input type="text" id="pay_range_box" name="query_pay_range" value="<%= @the_job_posting.pay_range %>">
      </div>

      <div>
        <label for="employer_id_box">
          Employer
        </label>

        <input type="text" id="employer_id_box" name="query_employer_id" value="<%= @the_job_posting.employer_id %>">
      </div>

<!--      <div>
        <label for="bookmarked_jobs_count_box">
          Bookmarked jobs count
        </label>

        <input type="text" id="bookmarked_jobs_count_box" name="query_bookmarked_jobs_count" value="<%#= @the_job_posting.bookmarked_jobs_count %>">
      </div>-->

      <button>
        Update job posting
      </button>
    </form>
  </div>
</div>

<hr>